### ISSUE TITLE
When logged in as a student, a missing template error is thrown if user tried to access the grades show.

### ISSUE THREAD

**Issue by dankb82** [tiyd-rails-2016-01/grade_master#43]
I'm thinking we don't even need the show link. When logged in as a student, the user can click "view grades" which bring an index of that student's grades.  It seems having a show page as well isn't necessary.

**Comment by stevengcooper** [comment]
I agree.  We took it off of Daniel and Kevin's branch. It's overkill to have the link there.

**Comment by katestud** [comment]
Anjana may have just pushed this up?
