### ISSUE TITLE
Multiple users can be associated with the same Teacher, Student, Parent

### ISSUE THREAD

**Issue by anjanamohanty** [tiyd-rails-2016-01/grade_master#55]
To recreate:
1. Go to users page logged in as Teacher
2. Create new user
3. Associate with existing teacher/student/parent
4. Submit form
5. Go back to users index and see multiple entries for same id

**Comment by byarsawich** [comment]
works for creating a new user, but won't work on editing a user.  chagnes are stored on the github_oauth branch if anyone else wants to try it.

**Comment by byarsawich** [comment]
fixed and submited pull request
